version: "3.7"

services:
  db:
    container_name: database-postgres
    #image: postgres:12-alpine
    image: postgres:11.5-alpine
    volumes:
      - /mnt/c/Users/wande/database/data:/var/lib/postgresql/data/pgdata
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default
    restart: always