version: "3.7"

services:
  backend:
    container_name: backend-fastapi
    command: "uvicorn app:app --reload --use-colors --host 0.0.0.0 --port 80"
    build: ./
    env_file: .env
    ports:
      - 8000:80ß
    depends_on:
      - db
    links:
      - db:db
    networks:
      - default

  db:
    container_name: database-postgres
    image: postgres:12-alpine
    volumes:
      - /home/docker/volumes/db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default
    restart: always