version: "3.7"

services:
  # backend:
  #   container_name: backend-fastapi
  #   command: "uvicorn app:app --reload --use-colors --host 0.0.0.0 --port 80"
  #   build: ./
  #   env_file: .env
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - db
  #   links:
  #     - db:db
  #   networks:
  #     - default

  db:
    container_name: database-postgres
    image: postgres:12-alpine
    volumes:
      - .data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default