version: "3.7"

services:
  db:
    container_name: database-postgres
    image: postgres:12-alpine
    volumes:
      - .data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default