version: "3.7"

services:
  app:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./dockerfile
    env_file: .env
    ports: 
      - 3000:3000
    networks:
      - default
